"""
Contains log messages and constants
"""

# status bar
MSG_BT = '[Method %s - Level %s] generating bad twin ...'
MSG_GT = '[Method %s - Level %s] generating good twin ...'
MSG_SYNC = '[Method %s - Level %s] synchronizing twins ...'
MSG_RES = '[Method %s - Level %s] saving intermediate results ...'
MSG_COND_VER = '[Method %s - Level %s] verifying condition C%s ...'
MSG_COND_SAT = '[Method %s - Level %s] condition C%s%ssatisfied ...'
MSG_LEV_SAT = '[Method %s - Level %s] diagnosability level%ssatisfied ...'
MSG_MAX_LEV = '[Method %s] maximum diagnosability level: %s'
MSG_TRUE_LEV = '[Method %s] checked diagnosability level: %s (true)'

# error messages
# - config
PARAMS_ERROR = 'Error(s) found in configuration file'

# - xml
XML_SYNTAX_ERROR = '%s'
LANGUAGE_NOT_ALIVE_ERROR = 'The language generated by the automaton in not alive over its events alphabet.'
STATE_NAME_ERROR = 'Invalid state name %s. Character \',\' is not allowed.'
ZERO_INITIAL_STATES_ERROR = 'No initial state found. Exactly one state must be marked as initial.'
MULTIPLE_INITIAL_STATES_ERROR = 'Too many initial states found. Exactly one state can be marked as initial.'
NO_OBSERVABLE_TRANSITIONS_ERROR = 'No observable transitions found. At lest one transition must be marked as observable'
NO_FAULT_TRANSITIONS_ERROR = 'No fault transitions found. At least one transition must be marked as fault'
MULTIPLE_ATTRIBUTES_TRANSITIONS_ERROR = 'Too many attributes for a transition. At most one attribute can be assigned to a transition'
NO_EVENT_IN_OBSERVABLE_TRANSITION_ERROR = 'No event in observable transition found. Observable transitions must have an event'
EVENT_IN_UNOBSERVABLE_TRANSITION_ERROR = 'Event in unobservable transition found. Unobservable transitions must have no events'
EVENT_NAME_ERROR = 'Invalid event name %s. Characters \'//\' and \'+\' are not allowed.'

# - random
STATES_TRANSITIONS_NUMBER_ERROR = 'The number of transitions must be greater or equal than the number of states'
ZERO_OBSERVABLE_TRANSITIONS_ERROR = 'The number of observable transitions must be greater or equal than 1'
OBSERVABLE_EVENTS_TRANSITIONS_NUMBER_ERROR = 'The cardinality of events alphabet must be less or equal than the number of observable transitions'
ZERO_FAULT_TRANSITIONS_ERROR = 'The number of fault transitions must be greater or equal than 1'
TOTAL_TRANSITIONS_NUMBER_ERROR = 'The sum of observable transitions and of fault ones must be less or equal than the total number of transitions'
MAX_ATTEMPTS_ERROR = 'Maximum number of attempts exceeded'

# separators
LEV_SEP = '-' * 70
METH_SEP = '#' * 70
END_LEV_SEP = '\\n'

# message types
TYPE_METH_SEP = 0
TYPE_COLOR_CHANGE = 1
TYPE_MSG_TWIN = 2
TYPE_MSG_RES = 3
TYPE_LEV_SAT = 4
TYPE_PARAMS_ERROR = 5
TYPE_FINISH = 6
TYPE_END_LEV = 7